### PR TITLE
I hate doing these PRs

### PR DESCRIPTION
**Pull request by ghost**
## Checklist:

- [ ] My code follows the code style of this project. (CI will test it anyway and also needs approval)
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.

### CODE REVIEW

**Comment by genofire** [comment]
You forgot the branch in the url.

**Comment by genofire** [comment]
okay, i would merge, if you retitle the commit to something with information

**Comment by genofire** [comment]
next time you could use git reword and rename the PR :+1: 
 (link to #7 )

**Comment by ghost** [comment]
not possible with the github web interface though

**Pull request closed without merging**
